baseURL: "https://blog.husky-dev.me"
languageCode: "uk"
defaultContentLanguage: "uk"
title: "Husky Blog"
theme: "PaperMod"
timeout: "5m"

taxonomies:
  category: categories
  tag: tags
  series: series

menu:
  main:
    - identifier: namibia
      name: "ğŸ‡³ğŸ‡¦ ĞĞ°Ğ¼Ñ–Ğ±Ñ–Ñ"
      url: "/series/namibia/"
      weight: 1
    - identifier: kilimanjaro
      name: "ğŸ‡¹ğŸ‡¿ ĞšÑ–Ğ»Ñ–Ğ¼Ğ°Ğ½Ğ´Ğ¶Ğ°Ñ€Ğ¾"
      url: "/series/kilimanjaro/"
      weight: 2
    - identifier: singapore
      name: "ğŸ‡¸ğŸ‡¬ Ğ¡Ñ–Ğ½Ğ³Ğ°Ğ¿ÑƒÑ€"
      url: "/series/singapore/"
      weight: 3
    - identifier: new-zealand
      name: "ğŸ‡³ğŸ‡¿ ĞĞ¾Ğ²Ğ° Ğ—ĞµĞ»Ğ°Ğ½Ğ´Ñ–Ñ"
      url: "/series/new-zealand/"
      weight: 4
    - identifier: work-and-travel
      name: "ğŸ‡ºğŸ‡¸ USA"
      url: "/series/work-and-travel/"
      weight: 5
    - identifier: sport
      name: "ğŸƒâ€â™‚ï¸ Ğ¡Ğ¿Ğ¾Ñ€Ñ‚"
      url: "/categories/sport/"
      weight: 6
    - identifier: books
      name: "ğŸ“š ĞšĞ½Ğ¸Ğ³Ğ¸"
      url: "/categories/books/"
      weight: 7
    - identifier: diy
      name: "ğŸ› ï¸ DIY"
      url: "/categories/diy/"
      weight: 8

params:
  defaultTheme: auto
  assets:
    disableFingerprinting: false
  DateFormat: "2 January, 2006"
  ShowPostNavLinks: true
  cover:
    linkFullImages: true
  homeInfoParams:
    Title: "ĞŸÑ€Ğ¸Ğ²Ñ–Ñ‚ ğŸ¤š"
    Content: "ĞœĞµĞ½Ğµ Ğ·Ğ²Ğ°Ñ‚Ğ¸ Ğ¯Ñ€Ğ¾ÑĞ»Ğ°Ğ². Ğ¯ Ğ¿Ñ€Ğ¾Ğ³Ñ€Ğ°Ğ¼Ñ–ÑÑ‚. Ğ›ÑĞ±Ğ»Ñ Ğ¿Ñ€Ğ¾Ğ³Ñ€Ğ°Ğ¼ÑƒĞ²Ğ°Ğ½Ğ½Ñ, Ğ¿Ğ¾Ğ´Ğ¾Ñ€Ğ¾Ğ¶Ñ– Ñ– ÑĞ¿Ğ¾Ñ€Ñ‚. Ğ Ñ†Ğµ Ğ¼Ñ–Ğ¹ Ğ¿ĞµÑ€ÑĞ¾Ğ½Ğ°Ğ»ÑŒĞ½Ğ¸Ğ¹ Ğ±Ğ»Ğ¾Ğ³."
  showReadingTime: true
  socialIcons:
    - name: "instagram"
      url: "https://www.instagram.com/husky.dev/"
    - name: "facebook"
      url: "https://fb.me/huskydev"
    - name: "twitter"
      url: "https://twitter.com/HuskyDevUA"
    - name: "github"
      url: "https://github.com/husky-dev"
    - name: "email"
      url: "mailto:jaroslav@husky-dev.me"

defaultContentLanguage: "uk"

languages:
  uk:
    weight: 1
    languageName: "ğŸ‡ºğŸ‡¦"
  en:
    weight: 2
    languageName: "ğŸ‡ºğŸ‡¸"
    params:
      homeInfoParams:
        Title: "Hello!"
        Content: "My name is Jaroslav. I am a programmer. I love programming, traveling and sports."
    menu:
      main:
        - identifier: diy
          name: "ğŸ› ï¸ DIY"
          url: "/categories/diy/"
          weight: 8
      
outputs:
  home:
    - HTML
    - RSS
    - JSON 
