baseURL: "https://blog.husky-dev.me"
languageCode: "uk"
defaultContentLanguage: "uk"
title: "ğŸ‘¨â€ğŸ’» Husky Blog"
theme: "PaperMod"
timeout: "5m"

taxonomies:
  category: categories
  tag: tags
  series: series

menu:
  main:
    - identifier: kilimanjaro
      name: "ğŸ‡¹ğŸ‡¿ ĞšÑ–Ğ»Ñ–Ğ¼Ğ°Ğ½Ğ´Ğ¶Ğ°Ñ€Ğ¾"
      url: "/series/kilimanjaro/"
    - identifier: namibia
      name: "ğŸ‡³ğŸ‡¦ ĞĞ°Ğ¼Ñ–Ğ±Ñ–Ñ"
      url: "/series/namibia/"
    - identifier: work-and-travel
      name: "ğŸ‡ºğŸ‡¸ USA"
      url: "/series/work-and-travel/"
    - identifier: sport
      name: "ğŸƒâ€â™‚ï¸ Ğ¡Ğ¿Ğ¾Ñ€Ñ‚"
      url: "/categories/sport/"
    - identifier: books
      name: "ğŸ“š ĞšĞ½Ğ¸Ğ³Ğ¸"
      url: "/categories/books/"
    - identifier: diy
      name: "ğŸ› ï¸ DIY"
      url: "/categories/diy/"

params:
  defaultTheme: auto
  assets:
    disableFingerprinting: true
  DateFormat: "2 January, 2006"
  ShowPostNavLinks: true
  cover:
    linkFullImages: true
  homeInfoParams:
    Title: "ĞŸÑ€Ğ¸Ğ²Ñ–Ñ‚ ğŸ¤š"
    Content: "ĞœĞµĞ½Ğµ Ğ·Ğ²Ğ°Ñ‚Ğ¸ Ğ¯Ñ€Ğ¾ÑĞ»Ğ°Ğ². Ğ¯ Ğ¿Ñ€Ğ¾Ğ³Ñ€Ğ°Ğ¼Ñ–ÑÑ‚, Ğ»ÑĞ±Ğ»Ñ ÑĞ¿Ğ¾Ñ€Ñ‚ Ñ– Ğ¿Ğ¾Ğ´Ğ¾Ñ€Ğ¾Ğ¶Ñ–. Ğ Ñ†Ğµ Ğ¼Ñ–Ğ¹ Ğ¿ĞµÑ€ÑĞ¾Ğ½Ğ°Ğ»ÑŒĞ½Ğ¸Ğ¹ Ğ±Ğ»Ğ¾Ğ³"
  showReadingTime: true
  socialIcons:
    - name: "instagram"
      url: "https://www.instagram.com/husky.dev/"
    - name: "facebook"
      url: "https://www.facebook.com/snipter"
    - name: "twitter"
      url: "https://twitter.com/HuskyDevUA"
    - name: "github"
      url: "https://github.com/husky-dev"
    - name: "email"
      url: "mailto:hello@husky-dev.me"
      
outputs:
  home:
    - HTML
    - RSS
    - JSON 
